/** Generated by scripts/prepare-hero-fonts.mjs — do not edit manually. */
import localFont from "next/font/local";

export const canela = localFont({
  src: [
    { path: "../assets/fonts/canela/Canela-Thin.otf", weight: "100", style: "normal" },
    { path: "../assets/fonts/canela/Canela-Light.otf", weight: "300", style: "normal" },
    { path: "../assets/fonts/canela/Canela-Regular.otf", weight: "400", style: "normal" },
    { path: "../assets/fonts/canela/Canela-LightItalic.otf", weight: "300", style: "italic" },
    { path: "../assets/fonts/canela/Canela-Medium.otf", weight: "500", style: "normal" },
  ],
  variable: "--font-canela",
  display: "swap",
  fallback: ["Georgia", "Times New Roman", "serif"],
});

export const heroFontsReady = true;
